    人生苦短，我用python
# python第四课

### 课程安排

    1、numpy
    2、pandas
    3、matplotlib

### numpy

    数组跟列表，列表可以存储任意类型的数据，而数组只能存储一种类型数据

In [12]:
import array

In [14]:
a = array.array('i', range(10))

In [19]:
# 数据类型必须统一
a[1] = 's'

TypeError: an integer is required (got type str)

In [17]:
a

array('i', [0, 10, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np

#### 从原有列表转换为数组

In [25]:
a_list = list(range(10))
b = np.array(a_list)
type(b)

numpy.ndarray

生成数组

In [31]:
a = np.zeros(10, dtype=int)
print(type(a))
# 查看数组类型
a.dtype

<class 'numpy.ndarray'>


dtype('int64')

In [33]:
a = np.zeros((4,4), dtype=int)
print(type(a))
# 查看数组类型
print(a.dtype)
a

<class 'numpy.ndarray'>
int64


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.ones((4,4), dtype=float)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [35]:
np.full((3,3), 3.14)

array([[ 3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14]])

In [36]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
np.full_like(a, 4.12, dtype=float)

array([[ 4.12,  4.12,  4.12,  4.12],
       [ 4.12,  4.12,  4.12,  4.12],
       [ 4.12,  4.12,  4.12,  4.12],
       [ 4.12,  4.12,  4.12,  4.12]])

### random

In [3]:
print(random.randint(5,10))
print(random.random())

NameError: name 'random' is not defined

In [6]:
np.random.random((3,3))

array([[ 0.44163582,  0.62473355,  0.37709153],
       [ 0.76491027,  0.40704266,  0.60937983],
       [ 0.43651869,  0.63857332,  0.6901747 ]])

In [7]:
# 经常会用到
np.random.randint(0, 10, (5, 5))

array([[7, 8, 3, 7, 6],
       [7, 1, 6, 9, 1],
       [9, 0, 6, 9, 7],
       [0, 8, 0, 2, 2],
       [5, 5, 8, 7, 7]])

### 范围取值

In [87]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [94]:
# 经常用到
np.linspace(0, 3, 10)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ,  1.33333333,
        1.66666667,  2.        ,  2.33333333,  2.66666667,  3.        ])

In [97]:
# n维的单位矩阵
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

| Data type	    | Description |
|:---------------|:-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats|

### 访问数组中元素

In [11]:
# 嵌套列表的元素访问
var = [[1,2,3], [3,4,5], [5,6,7]]
var[0][0]

1

In [12]:
# 数组中元素的访问
a = np.array(var)
a[-1][0]

5

In [13]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [14]:
# 这两种访问方式是等价的
a[2, 0], a[2][0]

(5, 5)

In [120]:
# 数组切片
a[:2, :2]

array([[1, 2],
       [3, 4]])

In [17]:
# 同上边的方式是不等价的
a[:2][:2]

array([[1, 2, 3],
       [3, 4, 5]])

### 数组属性

In [129]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [18]:
# 维度
print(a.ndim)
# shape
print(a.shape)
# size
print(a.size)
# dtype
print(a.dtype)
# a.itemsize（每个元素的字节数）
print(a.itemsize)
# nbytes
print(a.nbytes)

2
(3, 3)
9
int32
4
36


### 运算

In [20]:
a = np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
print(a + 10)
print(a - 10)
print(a * 100)

[10 11 12 13 14 15 16 17 18 19]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[  0 100 200 300 400 500 600 700 800 900]


In [150]:
a = np.full((3,3), 1.0, dtype=float)
a + 10 # 等价于 np.add(a, 10)

array([[ 11.,  11.,  11.],
       [ 11.,  11.,  11.],
       [ 11.,  11.,  11.]])


| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


In [155]:
a = np.linspace(0, np.pi, 5)
b = np.sin(a)
print(a)
print(b)

[ 0.          0.78539816  1.57079633  2.35619449  3.14159265]
[  0.00000000e+00   7.07106781e-01   1.00000000e+00   7.07106781e-01
   1.22464680e-16]


### 统计类型

In [32]:
# 求和
print(sum([1,2,3,4,5,6]))
# 数组一维求和
a = np.full(10, 2.3)
print(sum(a))
# 数组多维求和
a = np.array([[1,2],[3,4]])
print(sum(a))

# np.sum 求和
np.sum(a)
np.sum(a, axis=1)
np.max(a, axis=1)

21
23.0
[4 6]


array([2, 4])

In [33]:
n = np.random.rand(10000)

array([ 0.9691341 ,  0.36896102,  0.32846151, ...,  0.44802557,
        0.79781513,  0.20246048])

### notebook使用小技巧

%timeit 代码 ; 此方法来判断程序的执行效率

In [38]:
print('sum函数耗时：')
%timeit sum(n)
print('np.sum函数耗时：')
%timeit np.sum(n)

sum函数耗时：
1.57 ms ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
np.sum函数耗时：
8.9 µs ± 423 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 由上代码可已看出np.sum的执行效率高，推荐使用

### 比较

In [178]:
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
a > 3

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [180]:
a != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [181]:
a == a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

| Operator	    | Equivalent ufunc    || Operator	   | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |

In [183]:
np.all(a>-1)

True

In [184]:
np.any(a>-1)

True

### 变形

In [40]:
a = np.full((2, 10), 1, dtype = float)
a

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [41]:
a.reshape(4, 5)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### 排序

In [43]:
l = [
    [1,2,3],
    [34,12,4],
    [32,2,33]
]
a = np.array(l)
a

array([[ 1,  2,  3],
       [34, 12,  4],
       [32,  2, 33]])

In [51]:
np.sort(a, axis = 1)

array([[ 1,  2,  3],
       [ 4, 12, 34],
       [ 2, 32, 33]])

### 拼接

In [53]:
a = np.array([1, 2, 3])
b = np.array([[0, 2, 4], [1, 3, 5]])

In [54]:
# 按行去连接
np.concatenate([b, b, b], axis = 0)

array([[0, 2, 4],
       [1, 3, 5],
       [0, 2, 4],
       [1, 3, 5],
       [0, 2, 4],
       [1, 3, 5]])

In [214]:
# 按列去连接
np.concatenate([b,b,b], axis=1)

array([[0, 2, 4, 0, 2, 4, 0, 2, 4],
       [1, 3, 5, 1, 3, 5, 1, 3, 5]])